# GUI -----------------------------------------------
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#fab387'
      - bold
    inactiveBorderColor:
      - '#89b4fa'
      - bold
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#fab387'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  authorColors:
    'Sam Gabel': '#fab387'
  showFileTree: false

promptToReturnFromSubprocess: false
notARepository: "quit"

# GIT ----------------------------------------------
git:
  # https://github.com/jesseduffield/lazygit/discussions/4348#discussioncomment-12362665
  mainBranches:
    - main
    - dev
    - development
  # disable auto fetching
  autoFetch: false
  commit:
    signOff: false
  # use delta for git diff
  paging:
    colorArg: always
    pager: delta --dark --paging=never
